# Local statistics only. NAT inclusion also controls local socket deltas in 4.4.7.
[netifyd]
enable_sink = no
upload_nat_flows = yes
export_json = yes

[socket]
listen_path[0] = /var/run/netifyd/netifyd.sock
dump_unknown_flows = yes

[protocols]
all=include
